### ISSUE TITLE
[xargs] Missing output in zsh

### ISSUE THREAD

**Issue by kevingimbel** [tldr-pages/tldr#1282] opened 2017-02-27 19:34 UTC
I just installed `tldr` and tried it with a few commands. They all worked but `xargs` just shows a broken template as seen below.

<img width="962" alt="screen shot 2017-02-27 at 20 25 43" src="https://cloud.githubusercontent.com/assets/2161714/23376157/70c252d2-fd2b-11e6-8226-8222871bd5ac.png">

My system: 

**MacOS:** Sierra (10.12.1)
**zsh:** 5.2 (x86_64-apple-darwin15.6.0)
**tldr:** 1.7.1

I looked at the template file but didn't see any obvious issue. https://github.com/tldr-pages/tldr/blob/master/pages/common/xargs.md

**Comment by agnivade** [comment] 2017-02-28 04:25
Thanks for reporting. This seems to be a dupe of https://github.com/tldr-pages/tldr-node-client/issues/139. Lets track that one. In future, please open an issue on the corresponding client page.

**Closed by agnivade** 2017-02-28 04:25 UTC
