### ISSUE TITLE
Terminal theme vs tldr blue background

### ISSUE THREAD

**Issue by rakanalh** [tldr-pages/tldr#323] opened 2015-11-18 15:38 UTC
I am using a theme on my CLI that doesn't render very well with tldr's blue background for descriptions.

![Imgur](http://i.imgur.com/GAAHavv.png)

**Comment by waldyrious** [comment] 2015-11-18 18:12
Which client are you using? (See #270)

**Comment by ostera** [comment] 2015-11-18 20:35
Should we optimize for readability and compatibility here? No decisions on colors but instead use bold for the commands so they stand out.

If colors are really a must, a simple .tldr file should be enough to specify a `background_color=#123123`

**Comment by rakanalh** [comment] 2015-11-18 20:44
I am using iTerm on Mac OSX with a Solarized Theme. Zsh (Agnostic theme).

**Comment by rprieto** [comment] 2015-11-19 03:25
Indeed, doesn't look great! I agree with @ostera & @waldyrious that the default should be nice & legible. The [node client](https://github.com/tldr-pages/tldr-node-client) supports a config file for colors, I'm not sure about others. However we could improve it to support bold/italics instead of colors, and as discussed in #256 it should probably be an opt-in. 

I'll leave this open until we know which client you're using, but we should raise an issue over there.

Also... the irony is not lost on me that issue #256 talks about using ANSI 8bit colors :smile:

**Comment by rakanalh** [comment] 2015-11-19 08:57
Oh sorry... that would be the python client which i installed using pip.

**Comment by waldyrious** [comment] 2015-11-19 09:37
> Oh sorry... that would be the python client which i installed using pip.

Ok, so this would be a duplicate of tldr-pages/tldr-python-client#7

**Comment by rprieto** [comment] 2015-11-19 12:05
Thanks, closing in flavour of the other issue then

**Closed by rprieto** 2015-11-19 12:05 UTC
