### ISSUE TITLE
xargs page malformed on Linux

### ISSUE THREAD

**Issue by metov** [tldr-pages/tldr#5196] opened 2021-01-27 23:39 UTC
The page for `xargs` doesn't show up right for me:

![Screen Shot 2021-01-27 at 3 38 04 PM](https://user-images.githubusercontent.com/51468504/106068663-bd86b080-60b5-11eb-81ed-facbeaf1214f.png)

However I don't see anything too wrong with the markdown: https://github.com/tldr-pages/tldr/blob/7c681eea51f59c42391e0eacd3f4d91f19552bd7/pages/common/xargs.md

I guess the inline backticks are being wrongly converted to newlines?

**Comment by MasterOdin** [comment] 2021-01-28 00:00
The Ubuntu `tldr` apt package is a very out of date [psibi/tldr-hs](https://github.com/psibi/tldr-hs). Any issues with it should be filed in that repo. It looks like the bug causing the bad rendering was https://github.com/psibi/tldr-hs/issues/11 which was fixed in the 0.3.1 release.

**Comment by sbrl** [comment] 2021-01-31 16:16
Closing as a duplicate of https://github.com/psibi/tldr-hs/issues/11. If the issue persists, please open a new issue against the repository associated with the client you're using :-)

**Closed by sbrl** 2021-01-31 16:16 UTC
Labels: clients, duplicate
