### ISSUE TITLE
How to handle mixed casing of titles and filenames

### ISSUE THREAD

**Issue by MasterOdin** [tldr-pages/tldr#5085] opened 2021-01-04 17:33 UTC
Typing this issue up from recent discussion on gitter.

Currently, most pages use filenames that are lowercased, even if the command that they document utilizes capital letters.

[common/pages/R.md](https://github.com/tldr-pages/tldr/blob/master/pages/common/R.md) is an example of a page who has the file name and title using capitals.

[windows/pages/get-content.md](https://github.com/tldr-pages/tldr/blob/master/pages/windows/get-content.md) is a page where the file name is lowercased and the title/command uses capitals.

While man itself is case sensitive (presumably given Linux's case sensitivity), I do not think it makes sense to apply this to tldr, given that people are using this repo on a range of systems, some case sensitive and some case insensitive. For example, macOS is case insensitive, and so it's possible to refer to any command listed with any capitalization (e.g. I could always use 
`Python3 /path/to/script.py`), and so mandating memorization of capitalization does not really make sense. Similarly, I could use `r` to refer to `R`.

My vote on the resolution of this would be:
1. Mandate all pages file names are always lowercased
2. Page title / command examples can be mixed case per whatever the recommended usage examples from developer are
3. `(page file name).toLowerCase() === (page title).toLowerCase()`

The benefits of this approach imo would be:
1. Easier to implement on clients if page file names are always lower cased (e.g. https://github.com/ostera/tldr.jsx/issues/166 would not happen)
2. Users can type any case for a string and get information back, leading to easier discoverability

**Comment by sbrl** [comment] 2021-01-04 17:39
I think for the linter to work the page name must exactly and case-sensitively match the page name, but I can't remember. So the linter needs to be considered here.

I like the idea of having page name in lowercase, but I'm somewhat concerned that if we encounter 2 commands with different functions but the same name and different casings we'll have an issue.

Murphy's Law: If it can happen, it will happen.

**Comment by bl-ue** [comment] 2021-01-04 17:46
+1 for title = pagename = lower.  @sbrl I can't think of any example where two commands _with the same name, but different casing, have different functionality_.  That **does not** seem likely at all, to me.

**Comment by MasterOdin** [comment] 2021-01-04 17:51
To add to this, letting in pages with different cases, but same letters (say `common/R.md` and `common/r.md`) will lead to weird irregularities in working on this repo (and maybe also clients) for people on Windows and macOS.

**Comment by sbrl** [comment] 2021-01-04 18:00
Oops, looks like my previoous comments didn't come out right. I'm in favour of:

 - **filename:** lowercase
 - **page title:** exactly matching the command name (case-sensitive)

**Comment by sbrl** [comment] 2021-01-04 18:02
Example of different commands, same letters:

```
$ r
Command 'r' not found, but can be installed with:
sudo apt install r-cran-littler
sbrl@Ramblewood:~$ R
Command 'R' not found, but can be installed with:
sudo apt install r-base-core
```

**Comment by bl-ue** [comment] 2021-01-04 18:06
Hmm...that's tricky.  I'm not sure what to do about that.  As @MasterOdin said, macOS is case-insensitive, and so is Windows, so that situation isn't possible on those OSes.

**Comment by MasterOdin** [comment] 2021-01-04 18:32
> I think for the linter to work the page name must exactly and case-sensitively match the page name, but I can't remember. So the linter needs to be considered here.

@sbrl The linter currently does not do anything with file names. Support for that is being added in https://github.com/tldr-pages/tldr-lint/pull/32 which I will update to support with the decision on this topic.

**Comment by MasterOdin** [comment] 2021-01-05 23:59
I have updated the PR above to include a rule mandating lowercase file names. Similar to what was done with 0.0.9 release, once 0.0.10 (or whatever) is released, I will make a new issue that bundles all pages that now fail validation into a single master issue to track updating them all.

**Comment by bl-ue** [comment] 2021-01-06 01:19
Nice.

**Comment by waldyrious** [comment] 2021-01-07 10:55
According to [this comment](https://github.com/tldr-pages/tldr-lint/pull/32#discussion_r553061948), a consensus hasn't been reached yet. Let's reopen and close once there's a clear agreement on how to proceed.

**Comment by waldyrious** [comment] 2021-01-07 11:04
My 2 cents: yes, there will be pages with the same name and different casing, but it's equally possible for two tools to exist with exactly the same name in the same platform (see https://github.com/Homebrew/homebrew-core/pull/65438 for an example). That means that allowing case differences may alleviate the problem somewhat, but will not solve it completely, while making things way too nuanced and potentially confusing for those used to case-insensitive platforms (not to mention potential git issues as @MasterOdin mentioned [above](https://github.com/tldr-pages/tldr/issues/5085#issuecomment-754119740)).

My vote, then, is to force all filenames to be lowercase, but allow the page titles to match the command's preferred name, as [originally proposed above](https://github.com/tldr-pages/tldr/issues/5085#issuecomment-754124415), as well as in the opening comment. Any objections?

**Comment by MasterOdin** [comment] 2021-01-07 12:02
The situation already exists within tldr of multiple commands with the same name:
* https://github.com/tldr-pages/tldr/blob/master/pages/linux/file-rename.md
* https://github.com/tldr-pages/tldr/blob/master/pages/linux/rename.md
* https://github.com/tldr-pages/tldr/blob/master/pages/linux/perl-rename.md
* https://github.com/tldr-pages/tldr/blob/master/pages/linux/prename.md

I would also like to express that it's not just git that will be a problem, it will also be actual usage of the client. If you have two pages `R.md` and `r.md`, I will be unable to view them with how the node client works. When the zip is downloaded and expanded, one of those files will clobber the other one (no guarantee which probably), and at best, trying to see `tldr R` and `tldr r` will show the same page, but at that point, I'd consider this undefined behavior so who knows.

**Comment by bl-ue** [comment] 2021-01-07 12:21
There will also be some commands with the exact same name and casing, for example the more [popular bat](https://github.com/sharkdp/bat) and less [popular bat](https://github.com/astaxie/bat), and the relevant issue: https://github.com/sharkdp/bat/issues/164 😄

**Comment by schneiderl** [comment] 2021-01-07 12:57
My opinion on this would be similar to @waldyrious.
But when this issue does happen, when someone tries to create a document with a name that is already being used by another command, how we plan on fixing it? 
Or will we consider that the first command to get there will own that page forever?

**Comment by sbrl** [comment] 2021-01-07 13:54
> My vote, then, is to force all filenames to be lowercase, but allow the page titles to match the command's preferred name, as originally proposed above, as well as in the opening comment. Any objections?

That sounds like a sensible thing to do. The filename should match the command name in lowercase then, I take it?

**Comment by waldyrious** [comment] 2021-01-07 19:11
> The filename should match the command name in lowercase then, I take it?

In most cases, yes, but we we can't make that an absolute rule because of the additional cases that @MasterOdin mentioned in [his comment](https://github.com/tldr-pages/tldr/issues/5085#issuecomment-756075176). More on this below.

> But when this issue does happen, when someone tries to create a document with a name that is already being used by another command, how we plan on fixing it?
> Or will we consider that the first command to get there will own that page forever?

A better approach IMO would be to handle these in a case-by-case basis. But maybe we can come up with a strategy that allows for disambiguation in all cases. Typically package managers use namespacing to resolve this issue, i.e. the tool is referred in the format `@owner/tool` or `@project/tool`. We already a version of this, somewhat, by splitting the tools by platform. We could further use the owner/project prefix for those that still conflict (i.e. `project-tool.md`, or `tool.project.md`). Thoughts?

**Comment by MasterOdin** [comment] 2021-01-07 20:15
This discussion is now veering into territory covered by #5071, which is directly discussing how to handle an actual existing instance of this (rename commands) that exists in the tldr repo.

**Comment by sbrl** [comment] 2021-01-07 22:26
Hrm. Sounds like the issue is complex enough that we can't really enforce any of this via linter rules, except maybe the "always lowercase" bit.

**Comment by waldyrious** [comment] 2021-01-07 23:11
> This discussion is now veering into territory covered by #5071, which is directly discussing how to handle an actual existing instance of this (rename commands) that exists in the tldr repo.

Drat! Sorry for the diversion. I'll try to follow the discussion there. In any case, for this one, I think we can all agree with (1) making all filenames lowercase, and (2) not forcing the filename to match the title within. All in favor say "aye"! :P

**Comment by bl-ue** [comment] 2021-01-07 23:14
Aye! 😄

**Comment by schneiderl** [comment] 2021-01-08 11:50
Aye! 😃

**Comment by sbrl** [comment] 2021-01-16 15:42
Aye!

lol

**Comment by waldyrious** [comment] 2021-01-23 11:40
In retrospect, I should have asked whether anyone has objections :)

Anyway, there doesn't seem to be objections, so the only thing left to do is to implement the rules in the linter repo. We can close this issue once that's done :)

**Comment by bl-ue** [comment] 2021-01-25 15:48
@waldyrious

>and (2) not forcing the filename to match the title within.

You mean they don't have to match case or they don't have to match at all?

**Comment by sbrl** [comment] 2021-01-31 15:54
@bl-ue I think the idea there is that they don't have to match case.

**Closed** 2021-02-08 01:02 UTC
Labels: decision, syntax

**Comment by schneiderl** [comment] 2021-02-08 01:07
This got closed after [this](https://github.com/tldr-pages/tldr-lint/pull/42)got merged.

I believe the merged PR covers all the topics we discussed here.
Fixes for the aforementioned pages will be kept track of [here.](https://github.com/tldr-pages/tldr/issues/5255)

If anyone still have anything to discuss on this matter, please reopen the issue.

**Comment by bl-ue** [comment] 2021-03-01 15:34
I wonder if clients will support this.  e.g. `tldr eye3D` might fail for some clients because `eye3D` is documented in `eye3d.md` 🤔
