### ISSUE TITLE
page request: ip-route-show

### ISSUE THREAD

**Issue by kamalmost** [tldr-pages/tldr#7568] opened 2021-12-22 10:39 UTC

**Comment by d4n3sh** [comment] 2022-02-14 12:33
@kamalmost 

The page is available at [ip-route.md](https://github.com/tldr-pages/tldr/blob/main/pages/linux/ip-route.md)

**Comment by patricedenis** [comment] 2022-07-29 07:44
Hi, as said by @d4n3sh the issue is already been addressed by #5696.
Would you like some other examples?

**Comment by marchersimon** [comment] 2022-07-29 07:56
The current `ip route` page does however not really document `ip route show`, which itself has a lot of subsubsubcommands.

**Comment by patricedenis** [comment] 2022-10-05 20:49
Yes, that's right.
I will see if I can add some extra details on this one.

**Closed** 2022-11-08 13:57 UTC
Labels: new command, help wanted
