### ISSUE TITLE
Ping relevant people automatically with MentionBot

### ISSUE THREAD

**Issue by ostera** [tldr-pages/tldr#1068] opened 2016-09-17 10:36 UTC
As per https://github.com/tldr-pages/tldr/issues/980#issuecomment-235233941

@agnivade:

> This is going to be indispensable as we grow bigger. IMO maintaining a list of commands with their contributors will be too much to keep on updating. Instead, I propose, something like this [mention-bot](https://github.com/facebook/mention-bot). Its pretty neat, and I have seen this being used in a lot of projects.

**Comment by agnivade** [comment] 2016-09-29 19:13
Mention bot is setup. Lets see how it goes for a few days and I will add a setup file to further tune its settings if needed.

**Comment by waldyrious** [comment] 2016-09-29 19:28
Awesome! 🎉 +💯

**Comment by agnivade** [comment] 2016-10-05 17:37
Looks good to me so far. Closing it.

**Comment by waldyrious** [comment] 2017-09-06 16:08
Mention-bot doesn't seem to be working lately... any hints to what could be the problem? /cc @agnivade, @vjeux.

Perhaps we could try [running it ourselves](https://github.com/facebook/mention-bot#how-to-contribute-or-run-your-own-bot)? /cc @sbrl.

**Comment by agnivade** [comment] 2017-09-06 18:34
Tracking issue here - https://github.com/facebook/mention-bot/issues/230

**Comment by sbrl** [comment] 2017-09-07 14:39
Looks like it's broken for other people too, so I'd want to wait until that issue is fixed / we have more information before running it myself. I wonder how difficult it would be to build the functionality into our existing `tldr-bot`? We can list the committers for a file in git with something like this already:

```
git log filename | grep -i "Author:" | sort | uniq | cut -d' ' -f2-
```

....though I suspect that it would be the GitHub API that we'd need to deal with. It would simplify the services running on my server, at least :-)

**Comment by waldyrious** [comment] 2017-09-07 15:42
As a side note, it would be great if we could use [github's "owners" bot](https://github.com/probot/owners) (or the now natively integrated [code owners](https://github.com/blog/2392-introducing-code-owners) feature. Unfortunately, neither has an option to automatically detect appropriate owners (original committer of a file and all those who modified it). The they are implemented, we would have to manually maintain that mapping in an OWNERS file, which is unfeasible :(

@bkeepers, would such a feature be in-scope for probot-owners, or is that bot going to be deprecated now that its functionality is provided natively?

**Comment by waldyrious** [comment] 2017-09-07 15:43
> though I suspect that it would be the GitHub API that we'd need to deal with. It would simplify the services running on my server that way, at least :-)

Maybe https://github.com/probot/github-app could help in this regard?

**Comment by bkeepers** [comment] 2017-09-07 16:10
> @bkeepers, would such a feature be in-scope for probot-owners, or is that bot going to be deprecated now that its functionality is provided natively?

Still to be determined if it will be deprecated. I know some people don't love how the new code owners feature is implemented, so I think there is room for both to exist.

I would _love_ to have mention-bot functionality implemented as a GitHub App. I looked into it when building the owners app, but unfortunately mention-bot screen-scrapped the GitHub UI to get blame history (which I suspect is why it is now broken).

Let me know if you want to work on something together. I'd be happy to help out.

**Comment by waldyrious** [comment] 2017-09-07 16:40
Thanks for the info and quick response! @sbrl does this sound like something you'd want to give a try?

**Comment by sbrl** [comment] 2017-09-07 21:31
@waldyrious Possibly. I've just been looking into the tldr-bot source, and while my python is a bit rusty, it looks like a fairly simple task actually to update it - it's just testing it that might prove challenging! @agnivade, how do you test tldr-bot's logic?

We could use [this github api method](https://developer.github.com/v3/repos/commits/#list-commits-on-a-repository) to search for commits made on a file, and parse the resulting list of commits into a list of usernames that might make good reviewers.

We'd have to be careful to only do the mention once, and not every time a commit is made to a PR though. What kind of git hook is in use at the moment?

**Comment by sbrl** [comment] 2017-09-07 21:35
Also, there's a "code owners" feature? What is it and what's wrong with it? Fromt eh description on that blog post, it sounds just like @mention-bot - I'm confused.

**Comment by agnivade** [comment] 2017-09-08 17:53
> @agnivade, how do you test tldr-bot's logic?

I made a dummy PR. Intentionally made it to fail and confirmed that the bot catches it and updates the PR.

**Comment by waldyrious** [comment] 2017-09-09 14:59
> there's a "code owners" feature? What is it and what's wrong with it? From the description on that blog post, it sounds just like @mention-bot - I'm confused.

@sbrl I tried to answer precisely that question when I wrote

> Unfortunately, **neither has an option to automatically detect appropriate owners** (original committer of a file and all those who modified it). The way they are implemented, we would have to manually maintain that mapping in an OWNERS file, which is unfeasible :(

What part of that do you find confusing?

**Comment by sbrl** [comment] 2017-09-09 15:53
Ah, right! I think I see now! GitHub's official description is rather vauge :P

**Comment by sbrl** [comment] 2017-09-09 16:18
@agnivade uhh ok! Looks like I may end up creating a bunch of dummy PRs then :package: 

Any idea on the current git hook in use?/

**Comment by agnivade** [comment] 2017-09-09 18:55
There's no git hook in use. There's a travis hook in use, if that's what you are asking. It pipes the test result output to send_to_bot.py. The script gets the test results POSTs it to the api endpoint listening on your server.

**Comment by sbrl** [comment] 2017-09-10 19:11
Ahhh ok! I didn't realise :P Ok, in that case then if it's possible, a git(hub?) hook for new PRs would simplify things a whole bunch. Is there such a thing?

**Comment by agnivade** [comment] 2017-09-11 18:26
I don't see how it will simplify things. Its a hook at the end of the day, whether its coming from Travis or Github doesn't really matter. 

If you mean it will simplify things if you try to merge the tldr bot with the mention bot, then yes, that might be true because the github hook does send some additional metadata for the PR.

**Comment by sbrl** [comment] 2017-09-11 20:51
@agnivade I assume that we'd want our mentionbot implementation to send it's message every time a commit is made to a PR then?

**Comment by sbrl** [comment] 2017-09-11 21:07
@waldyrious I think it could work in either. I'm a little bit wary of running 2 separate processes /  services on my server though, so if we're talking about the hosted version of probot then probot-owners would probably be my preference.

If probot-owners isn't the publicly-hosted version of probot and would need to run on my server, I'd much prefer to integrate the functionality into tldr-bot in order to keep the service on my server simple (I discovered just how much configuration I'd done when I migrated from one server to another!).

**Comment by waldyrious** [comment] 2017-09-12 00:26
I think using the hosted version of probot-owners would be the best choice, since we could help identify potential issues that would affect other users as well. If that makes it easier for you, even better :)

**Comment by agnivade** [comment] 2017-09-12 06:19
> I assume that we'd want our mentionbot implementation to send it's message every time a commit is made to a PR then?

That would be too much IMO. Just do it only when a new PR is created.

**Comment by agnivade** [comment] 2017-10-12 06:39
@sbrl - We can set up mention bot ourselves in your server. I was going to do that, but I forgot the username I used to log in to your server. Can you remind me ? :sweat_smile:

**Comment by sbrl** [comment] 2017-10-13 20:34
@agnivade It's the `tldr-bot` user. Also, if it's going to be running on my server, I'd like to keep a very close eye on it. It's a Node.JS application - and I've experienced memory leaks with those before. Also, that's a _lot_ of heavy dependencies it requires - like multiple `babel` packages, according to the `package.json`. Are those _really_ necessary? It's a lot of weight for something that could in theory be much lighter.

**Comment by agnivade** [comment] 2017-10-13 22:16
Yes, those are necessary. Until we rewrite the logic ourselves, we are tied to this unfortunately. Let me know what you decide.

**Comment by zdroid** [comment] 2019-12-02 17:01
What's the state on this?

**Comment by agnivade** [comment] 2019-12-02 18:24
Thanks for following up on this @zdroid. From their repo:

> ** THIS REPO HAS BEEN ARCHIVED AND IS NO LONGER BEING ACTIVELY MAINTAINED **

I will close this since I don't see much sense in using an unmaintained product. We can look into using some alternative if we want. But that's for a new issue.

**Closed by agnivade** 2019-12-02 18:24 UTC
Labels: tooling

**Comment by sbrl** [comment] 2019-12-05 19:13
We could use something like this for language translations.
