### ISSUE TITLE
Add "see also" section to tldr pages

### ISSUE THREAD

**Issue by oxguy3** [tldr-pages/tldr#785] opened 2016-02-22 21:06 UTC
Very often, it seems like it'd be very likely that someone viewing page A might also find page B very useful. It could be very helpful if tldr pages were allowed to have a "See also" section at the bottom. For example, related or similar tools could link to each other (e.g. grep/ack, chgrp/chown, more/less, rm/shred, head/tail, etc). Another use case: sub commands and parent commands could all link to each other (e.g. git-whatever tools could link to git, and the `git` page could link to _all_ of them. ditto for csvkit and all of its tools).

A very simple implementation might look like:

```
# foo

> Most awesome tool ever.
...

## See also
- bar: another awesome tool
- baz: legacy version of foo
- qux: for reverting the effects of foo
```

It shouldn't be too hard for clients to implement this (command-line clients could probably get away with printing the raw markdown, more or less, and clients that already rely on a proper Markdown library won't need to do anything).

---

Issue #784 (which I've just submitted) goes hand-in-hand with this issue. If #784 and this issue were both implemented, then the See also section would definitely make use of the link syntax, and probably look more like this:

```
## See also
- [bar]: another awesome tool
- [common/baz]: cross-platform version of foo
- [qux]: for reverting the effects of foo
```

**Comment by igorshubovych** [comment] 2016-02-22 23:35
Just wonder, have you seen this?
https://github.com/tldr-pages/tldr-node-client/pull/81

**Comment by oxguy3** [comment] 2016-02-22 23:37
Dang, I had not seen that. Huh, well guess this is a bit redundant. >.<

**Comment by igorshubovych** [comment] 2016-02-22 23:54
Which one is redundant? Your variant or mine?

**Comment by oxguy3** [comment] 2016-02-23 01:35
Mine is redundant I guess, since yours was way earlier. That said, I do think it'd be nice if the see also list included descriptions of _why_ that particular tool was being linked. And also, being able to link to specific OS versions would be nice, like I showed below the horizontal rule in my original post.

**Comment by waldyrious** [comment] 2016-07-25 12:19
This is actually a duplicate of #481. I'll close this one and reopen the previous one :)

**Closed by waldyrious** 2016-07-25 12:19 UTC
Labels: clients, syntax
