### ISSUE TITLE
page request: Minecraft

### ISSUE THREAD

**Issue by Yutyo** [tldr-pages/tldr#5325] opened 2021-03-01 06:44 UTC
Minecraft is a game that has tons of commands, both simple and complicated. People create unbelievable stuff with them, even with the simplest set of commands. Opening a directory that contains pages regarding different Minecraft commands would be an outstanding feature.

An overall look to Minecraft commands: https://minecraft.gamepedia.com/Commands

A comprehensive repository of creations made with commands that players can put in single command block: https://onecmd.com/?sort=top

**Comment by owenvoke** [comment] 2021-03-01 19:29
I'm not entirely sure this falls under the purpose of tldr-pages 🤔 Minecraft commands are entered in game, rather than being called via the application (e.g. `minecraft {{command}}`)

**Comment by bl-ue** [comment] 2021-03-01 19:52
The original title was 'Directory request...' so maybe @Yutyo was thinking to add a new folder in `pages/` called `minecraft` e.g. `pages/minecraft/command.md`, which, I confess, I don't think is an entirely bad idea.

**Comment by Yutyo** [comment] 2021-03-01 20:45
> I'm not entirely sure this falls under the purpose of tldr-pages thinking Minecraft commands are entered in game, rather than being called via the application (e.g. `minecraft {{command}}`)

Currently in TLDR there are many commands which aren't usable in different OS and shell.

Yes, Minecraft commands are meant to be used in game rather than a separate shell but:
- Since 1.12, the game supports [functions](https://minecraft.gamepedia.com/Function_(Java_Edition)) which are written in files called .mcfunction
- Mods like [Computercraft](http://www.computercraft.info/) and [OpenComputers](https://ocdoc.cil.li/) which add computers to the game that literally have their own type of functional shell are quite popular among players and people commonly write software outside of the game and share them via Pastebin.
- Its possible to make a tldr mod for Minecraft that can make tldr-pages accessible via tldr {{command}} just like in shell. This can be even done without mods, by making an .mcfunction variation of tldr or going full crazy by creating a long single command block code that contains tldr pages and basic features to replicate what tldr does.

**Comment by owenvoke** [comment] 2021-03-02 10:33
I still think that's a bit of a weird thing to add, but open for debate about this obviously. 👍🏻

**Comment by sbrl** [comment] 2021-03-02 19:43
If we're talking about `minecraft` CLI arguments, then we should absolutely write a page on them! But in terms fo in-game commands, I'm unsure as to whether this is in-scope. The problem is that mods such as _WorldEdit_ and others add lots of new commands, so you'd need some way to identify which commands belong to which mod.

I'd suggest here that it would be better served as a separate project? Perhaps one could create a project like e.g. `tldr-mc` or something?

**Comment by MasterOdin** [comment] 2021-03-02 19:48
I agree with @sbrl, and would say that if you start adding minecraft sections, one might expect you'll also start adding console commands for other games (steam games, warcraft, etc.) and would blow up the scope of this project quite a bit.

**Comment by Yutyo** [comment] 2021-03-02 22:29
> I'd suggest here that it would be better served as a separate project? Perhaps one could create a project like e.g. `tldr-mc` or something?

Yeah, creating a separate project called `tldr-mc` makes sense.

**Comment by bl-ue** [comment] 2021-03-02 22:36
So I guess close this issue, right?

**Comment by sbrl** [comment] 2021-03-08 19:14
I'll close this issue for now, but we can always reopen if there's more to discuss.

**Closed by sbrl** 2021-03-08 19:14 UTC
Labels: new command
