### ISSUE TITLE
Define the brand name of the project

### ISSUE THREAD

**Issue by zdroid** [tldr-pages/tldr#1109] opened 2016-10-12 18:53 UTC
I noticed many names are used for this project, so I think it should be clarified. For example, you can find _TL;DR pages_, _tldr_, _tldr pages_ and _TLDR pages_ in various documents and website.

My suggestion is to use and _tldr_ for the name of npm package and _TLDR pages_ or _tldr pages_ for everything else. How does that sound?

**Comment by waldyrious** [comment] 2016-10-12 20:17
I normally don't like when brands attempt to enforce specific capitalization styling of the brand name, so I'd preferif we avoided the capitalized version, and the pedantic version with the semicolon. I suppose I'd either go with **tldr pages** or **tldr-pages**, but I'm open to hear other arguments.

**Comment by zdroid** [comment] 2016-10-12 20:21
Agree @waldyrious, I like that version more. *TLDR pages* sounds a bit too administrative. *tldr-pages* sounds cool in dev matter of cool.

**Comment by ostera** [comment] 2016-10-12 22:08
`tldr` has my vote.

**Comment by agnivade** [comment] 2016-10-20 03:41
I like **tldr pages**. Contrasts nicely with **man pages**.

**Comment by waldyrious** [comment] 2016-10-20 13:25
If we are willing to deviate a little more from the current name, we could consider rebranding as tldr.sh (which is akin to how many projects nowadays now use .js to indicate their context), or even go as far as ditching the hard-to-pronounce (and somewhat jargon-y) "tldr" altogether and pick something like "miniman" or "lil' man" :P just some fresh/wild (crazy?) ideas to spice up the discussion, not something I'm advocating at the moment.

Getting back down to earth, I suspect that "tldr-pages" may be better than "tldr pages" as it clearly identifies as a single word, in the absence of capitalization or formatting. But it's not a super-strong preference.

**Comment by zdroid** [comment] 2016-10-20 17:34
I agree with @waldyrious. `tldr-pages` seems the best at this moment.

**Comment by zdroid** [comment] 2016-11-21 18:23
Any news on this? Branding is an important part of the project.

**Comment by waldyrious** [comment] 2016-11-21 18:49
I'd like to hear @agnivade and @ostera's responses to my previous comment.

**Comment by ostera** [comment] 2016-11-21 21:19
I reeeeally need to setup tldr.sh

**Comment by agnivade** [comment] 2016-11-22 04:09
My preference is still "tldr pages", but I am okay with "tldr.sh" too.

**Comment by waldyrious** [comment] 2016-11-22 08:23
If tldr.sh is ok with you guys, I'd vote for it too.

@agnivade any thoughts about my arguments for using a hyphen? Besides those, we must also consider that using a space makes it awkward to refer to a single page. Is it a "tldr page" (which would mean the project identifies as "tldr" alone)? Using "tldr-pages page" would be consistent but admittedly kinda silly, so we could instead recommend something like "tldr-pages entry" for that case (that's one of the ways a branding guideline can be useful).

**Comment by agnivade** [comment] 2016-11-22 08:31
Referring to a single page is indeed an issue. My vote is for tldr.sh then.

**Comment by waldyrious** [comment] 2016-11-22 09:41
@zdroid, @ericbn, @Leandros, @fluxw42 what do you guys think? Any change since your last reactions?

**Comment by Leandros** [comment] 2016-11-22 11:29
My vote is for "tldr pages". The dash is overly verbose and doesn't fit well with how the english language is constructed.

**Comment by waldyrious** [comment] 2016-11-22 11:45
@Leandros what about the issues I mentioned [here](https://github.com/tldr-pages/tldr/issues/1109#issuecomment-255104786) and [here](https://github.com/tldr-pages/tldr/issues/1109#issuecomment-262176332)?

**Comment by zdroid** [comment] 2016-11-22 12:30
`tldr.sh` seems perfectly fine to me.

**Comment by Leandros** [comment] 2016-11-22 12:42
`tldr.sh` suggest that it's a program, library or is otherwise related to the linux shell, which is not the case?
Do we want that?

**Comment by ericbn** [comment] 2016-11-22 13:03
I have split thoughts here. On one hand I agree with @waldyrious that since we want to think about rebranding, we could consider something different than "tldr" (I always have to think about "too long didn't read" when typing, because I cannot think of a pronounceable form of "tldr"). On the other hand I like the name and the idea behind it, and then I would go with "tldr pages" (no hyphen)...

**Comment by ostera** [comment] 2016-11-24 06:57
For the record I meant the domain `www.tldr.sh`, which we have registered but haven't setup yet.

**Comment by waldyrious** [comment] 2017-05-16 11:26
So... shall we make a decision? The options raised here have been: (1) **tldr-pages**, (2) **tldr pages**, (3) **tldr.sh**, (4) **tldr**, and also (5) **miniman** and (6) **shortman**.

I would be OK with (1), (3) and (5).

(3) depends on @ostera's feedback -- what kind of setup are you planning for the domain? Would you like help keeping the domain registration? (Not sure how expensive it is.) I was thinking maybe we could start by simply making it a custom domain for http://tldr-pages.github.io, which is easy enough to setup, and later we could work on something more involved, to avoid delaying this much further.

IMO (2) would make it hard to distinguish when we're talking about the project and when we're talking about individual pages, and (4) would be too ambiguous with other uses of the term (and would make googling this a nightmare).

Thoughts?

**Comment by ostera** [comment] 2017-05-16 16:47
Hey! The domain is up :) should I configure the DNS to point to the github pages?

**Comment by agnivade** [comment] 2017-05-16 18:02
Cool, I am good with tldr.sh. I have a concern though - the org name is "tldr-pages". Are we going to change the org name too ?

**Comment by waldyrious** [comment] 2017-05-16 21:47
> Are we going to change the org name too ?

It would make sense, I suppose, and I'd personally be fine with that. We'd keep the primary identifier in our name, the "tldr" part, so that doesn't bother me too much.

**Comment by ostera** [comment] 2017-05-17 06:57
@waldyrious domain's A record pointing to Github -- http://tldr.sh -- you can take it from here 👍

**Comment by waldyrious** [comment] 2017-05-17 09:23
Annnd, it's working already :D that was easy :)

So now, **tldr.sh** is a viable option for the project name. Is everyone on board with that? Pinging @rprieto, @rubenvereecken, @igorshubovych.

**Comment by agnivade** [comment] 2017-05-17 10:27
If I try https://tldr.sh, I get a `NET::ERR_CERT_COMMON_NAME_INVALID`. Something we can do about it ?

**Comment by waldyrious** [comment] 2017-05-17 15:44
Hm... acording to this [GitHub help page](https://help.github.com/articles/securing-your-github-pages-site-with-https/):
> HTTPS is not supported for GitHub Pages using custom domains.

There might be alternatives, see [here](https://gist.github.com/cvan/8630f847f579f90e0c014dc5199c337b) and [here](https://hackernoon.com/set-up-ssl-on-github-pages-with-custom-domains-for-free-a576bdf51bc).

**Comment by agnivade** [comment] 2017-05-17 17:29
Ah .. going the cloudflare way. @ostera - is this something that you can do ? The nameserver change has to be done from your side.

**Comment by ostera** [comment] 2017-05-18 07:27
@agnivade @waldyrious Cloudflare setup done 👍 it'll take a few hours to work according to their website.

**Comment by agnivade** [comment] 2017-05-18 11:08
Works now. Can you enable HSTS also ?

**Comment by rprieto** [comment] 2017-05-18 11:59
I'm a little late to the party but I like "tldr pages", akin to "man pages". A single page is then a "tldr page" (man page). I think the name is still compatible with [tldr.sh](https://tldr.sh) which is a cool domain name!

If we choose to go with that, I've heard people pronounce it as `tilder` so we could do as many open-source projects do and mention it in the README `tldr pages (pronounced "tilder pages")`.

That being said I'm also happy with `tldr.sh` as the main branding or coming up with a newer fancy name like `miniman` too :)

**Comment by rubenvereecken** [comment] 2017-05-18 12:14
`miniman` just cracks me up

**Comment by waldyrious** [comment] 2017-05-18 12:25
I haven't pushed for `miniman` much, as I was the one to suggest it, but gotta say I really like it, too: it's self-descriptive, memorable, and very easy to pronounce (it kinda sounds like "minivan", an already existing word). Plus it doesn't include a jargon term, which better aligns with the project's ethos.

It really seems to tick all the boxes -- the only reason I haven't advocate adopting that name (but I'm tempted), is because "tldr" has definitely become sort of the main element of the project's "brand". But name changes have occurred for projects before, and large ones at that (e.g. IPython --> Jupyter comes to mind), without serious issues other than nostalgia of the old-timers, so it might well be a valid choice.

**Comment by mflint** [comment] 2017-05-25 22:17
Interesting thread!
Would you want the various clients to start using the "tldr.sh" name?

**Comment by waldyrious** [comment] 2017-06-15 09:18
@mflint I think we already have enough problems form all the clients calling themselves simply "tldr", so I wouldn't recommend going down that road. Of course, once we pick a definitive name for the project, the clients ought to refer to it (the project, not themselves) by that name, yeah.

@rubenvereecken I couldn't figure out whether your reaction to "miniman" is neutral, positive or negative. Would it be something you'd consider? (Just trying to tie up loose ends here.)

**Comment by rubenvereecken** [comment] 2017-06-20 10:01
Let's say I'm neutral about it.

**Comment by waldyrious** [comment] 2017-09-03 18:24
@rprieto, @agnivade, @ostera, @sbrl, @zdroid, @Leandros, @ericbn: I'd like to hear your thoughts on renaming the project `miniman` so we can make a decision here. I've already [listed a bunch of reasons](https://github.com/tldr-pages/tldr/issues/1109#issuecomment-302388562) that compel me to favor it above `tldr` / `tldr.sh`; @rubenvereecken is neutral about it per the comment immediately above, and @rprieto [said](https://github.com/tldr-pages/tldr/issues/1109#issuecomment-302383621) he is open to the idea.

Let's seize the 10,000th star event (#1464) to make a final call on this :)

**Comment by zdroid** [comment] 2017-09-03 18:34
I really support miniman. Never thought about it before, but it's pretty descriptive. :1st_place_medal: :+1:

**Comment by ericbn** [comment] 2017-09-03 20:06
Besides the "brand change" factor that @waldyrious mentioned [before](https://github.com/tldr-pages/tldr/issues/1109#issuecomment-302388562), I like `miniman`. Easier to remember than `tldr`...

Although the creative use of the TL;DR jargon gave the project something we can instantly attach to, maybe they way it's not easily pronounceable or beginner-friendly also lead to all the discussion above... Sad, but necessary, to see the name go...

**Comment by agnivade** [comment] 2017-09-04 04:36
Sorry to be "that" guy here 😛 , but I don't like miniman. Strong negative on that. I would really like to keep some part of "tldr" in the name. Losing that feels like losing the core identity of this project.

**Comment by rprieto** [comment] 2017-09-04 04:51
What about `howto`? Then on the CLI you'd type `howto tar`, `howto du` etc.

**Comment by Leandros** [comment] 2017-09-04 06:48
I like howto! It's descriptive and short.

**Comment by waldyrious** [comment] 2017-09-04 08:07
`howto` is descriptive and potentially even more self-explanatory than `miniman` (both are better than `tldr` IMO), because it subtly conveys what to expect (usage examples).

My only fear is that it's too generic and thus basically ungoogleable. Here's a table based on [the nominology post](http://messymatters.com/nominology/) I linked above:

Property | Description | tldr.sh | miniman | howto
-------- | ----------- | ------- | ------- | -----
Evocativity | Conveys at least a hint of what it’s naming | ★☆☆ | ★★☆ | ★★★
Brevity | Shorter = better | ★★★ | ★★☆ | ★★★
Greppability | Not a substring of common words | ★★★ | ★★☆ | ★★☆
Googlability | Reasonably unique (and domain name available) | ★★☆ | ★★☆ | ☆☆☆
Pronounceability | You can read it out loud when you see it | ☆☆☆ | ★★★ | ★★★
Spellability | You know how it’s spelled when you hear it | ☆☆☆ | ★★☆ | ★★☆
Playfulness | Catchy and memorable (e.g. a play on words) | ★★☆ | ★★★ | ☆☆☆

(I've excluded the "verbability" property, which all 3 score zero, to reduce visual noise, and added a "playfulness" property, which IMO is important for a good name to stick.)

It looks to me that objectively (to the extent that my scores are agreeable -- happy to adjust them to reflect consensus), "miniman" is the most balanced option, as it basically ticks all the "good project name" boxes.

**Comment by waldyrious** [comment] 2017-09-04 08:09
> Strong negative on that.

@agnivade can you clarify whether you dislike "miniman" in particular, or dislike anything that doesn't include "tldr" in general?

**Comment by agnivade** [comment] 2017-09-04 08:36
The latter.

**Comment by sbrl** [comment] 2017-09-04 14:35
Nice table! I'm inclined to say no to "howto", since it not only is difficult to google, but is additionally awkward to say - since it sounds like the beginning of a sentence.

**Comment by waldyrious** [comment] 2017-09-04 16:06
Good point @sbrl: the natural sentence would indeed be "how to use gcc?", not "how to gcc?". That said, most command names are pretty short and I could kind of see them used as a verb, e.g. "how to gcc <a file>" as a stand-in for "how to compile a file with gcc". This doesn't work in all cases, though.

**Comment by rprieto** [comment] 2017-09-04 23:00
That's true @waldyrious, I think it probably be the case with every name we have: it's hard to form a valid sentence on the command line :smile:.

The only thing I dislike about `miniman` is that it doesn't sound very serious. Will that put off part of the target audience? (although it might be hard to please both novice *nix users, and people who are command-line fans but need the occasional reminder).

**Comment by waldyrious** [comment] 2017-09-04 23:35
While "miniman" certainly has a playfulness to it, I also find it to be quite a good objective description of what we provide: compact manuals for the commands.

Yes, "mini-" is often used in a humorous/child-like context, but it is also used without any diminutive conotation (besides its literal meaning) in many common words, such as "minibar", "miniskirt", "minidisc", "miniseries", "Mini SUV", and [many more](https://en.wiktionary.org/wiki/Category:English_words_prefixed_with_mini-).

Even if that weren't the case, I think a user-base that readily adopted a project called "tldr-pages" would have no problem embracing a similarly playful (IMO) name :smile:

**Comment by rprieto** [comment] 2017-09-05 00:16
Never realised that Markdown was wordplay on Markup 😲 D'oh!

**Comment by ostera** [comment] 2017-09-05 06:29
`tldr(.sh) > miniman > anything else > tldr[-]pages > howto`

That’d be my short answer. So if we ain’t sticking to tldr for legacy reasons, I’d friggin love miniman to be the name.

**Comment by waldyrious** [comment] 2017-09-05 08:09
Great comment, @ostera. For a moment I was tempted to convert the other comments into a similar ranking for each participant in the discussion, tally up the votes and provide a table with numbers and total scores according to [various ranked-ballot counting methods](http://www.cs.wustl.edu/~legrand/rbvote/calc.html) (Borda, Schulze, etc.) — however, in my experience making these decisions based on cold numbers ends up feeling empty and unconvincing to most participants.

I believe at this point it is possible to identify a consensus (even if not unanimous) in the community, so I'll leave it to @rprieto to make the final decision.

(Note that the effects of the decision will likely not be effective _immediately_ — we'll need to then start discussing a transition plan, to avoid doing things too hastily.)

**Comment by ostera** [comment] 2017-09-05 08:34
I'd like to bring this from the [other discussion](https://github.com/tldr-pages/tldr/issues/1192#issuecomment-327084294), that I feel is very relevant to this conversation as well 

> Being playful and maintaining quality is a hard balance to keep, but so far we’ve done great work on curating these pages. Don’t see why we couldn’t try and check how the numbers do...after all Any rebranding is done to increase awareness and pull the brand value up ☝🏼 — @ostera

So keep in mind that this is a _branding_ discussion.

**Comment by zdroid** [comment] 2019-11-16 18:39
Seems like this has been solved.

**Comment by waldyrious** [comment] 2019-11-21 00:28
@zdroid I guess you're referring to the discussion at #2986. That one is about visual identity more than naming, as this one was. I will update the title of both issues to make that distinction clearer.

That said, re-reading this discussion, I feel that, while there were valid and even compelling arguments for a rebranding towards "miniman", the overall sentiment in the thread is one of strong attachment to the "tldr" name, so it makes sense to keep that in the core of our branding.

Still, I do bump into the issue of awkwardly having to refer to "tldr-pages pages" all the time, and people in the thread were not too keen on the usage of a hyphen to make the project name stand out as a single word, so I would suggest fully embracing the tldr.sh name. I'll reopen this issue to allow us to make a decision on that regard.

So, question for all those who were involved in this discussion (@zdroid, @ostera, @rprieto, @agnivade, @Leandros, @ericbn, @rubenvereecken, @mflint, @sbrl) as well as more recent members of the org (@mebeim, @pxgamer) and everyone in the community:

_In light of the discussed above, what do you guys think about consolidating **tldr.sh** as the project name?_

Please use the reactions so we can gauge the overall sentiment more easily. 👍 👎

**Comment by mebeim** [comment] 2019-11-21 01:10
I've seen this project almost always being called "TLDR pages" (with a variation of the case e.g. "tldr pages", "TLDR Pages" etc). I don't recall seeing any client referring to it differently. This project has been around for quite a while and this name is spread among countless repos, clients and documentation pages. I would therefore vote for "**TLDR Pages**" (or variation of the case) if I had to. Furthermore, "tldr.sh" just feels like a domain name to me.

**Comment by agnivade** [comment] 2019-11-21 03:42
There was no neutral reaction button, so I put "eyes" on it. As a single short name, "tldr.sh" is okay .. I guess. But as you can see .. there are concerns being raised with it looking like a domain name.

**Comment by waldyrious** [comment] 2019-11-21 10:14
Good point, @agnivade, I added that option above :)

As for looking like a domain name, I don't see why that's a bad thing; quite the contrary, it helps solidify the branding and is one less thing to memorize. Besides, it's shorter, more distinctive, and works as a single word (Incidentally, I find it interesting that a domain, rather than a shell script, is what the `.sh` extension evoked!)

I do want to hear about your experience with referring to the project's pages, due to the inherent duplication of "tldr pages page". Does that not bother you at all? If we decide to stick with "tldr pages" as the project name, maybe we could call the pages something else (files? documents? entries?), which would resolve the situation in a different way.

**Comment by mebeim** [comment] 2019-11-21 10:27
@waldyrious if the name is "TLDR pages" then a single page would be called either "TLDR pages page" or "TLDR page" (or maybe even "page of TLDR pages". It of course depends on the context though. There surely is no need to prefix it with "TLDR pages", most of the times it can be clearly understood what the term "page" refers to.

**Comment by mebeim** [comment] 2019-11-21 10:28
Also, adding to my previous comment: the project's organization GitHub name is "tldr-pages", which would make naming it differently rather confusing to me, so there's that.

**Comment by agnivade** [comment] 2019-11-21 11:41
We would have to rename the org of course. Github will redirect old links pointing to the old org - https://help.github.com/en/github/setting-up-and-managing-organizations-and-teams/renaming-an-organization.

**Comment by pxgamer** [comment] 2019-11-21 12:02
The only issue is that anyone can then take the old org name. 🤔

**Comment by ostera** [comment] 2019-11-21 12:06
At the risk of stating the obvious, remember the org name has *tons* of searchability value attached to it already.

Can you ask GitHub for a org level redirect?

**Comment by agnivade** [comment] 2019-11-21 12:14
> The only issue is that anyone can then take the old org name

They indeed can. But links to old repos will automatically redirect. Only a link to the exact org - "github.com/tldr-pages" will now point to the newly acquired org.

See the link above.

**Comment by mebeim** [comment] 2019-11-21 13:01
> At the risk of stating the obvious, remember the org name has tons of searchability value attached to it already.

This. Renaming the org will inevitably break this and also any script/code/auth token/**client** and whatever else uses that name to do anything.

**Comment by agnivade** [comment] 2019-11-21 15:47
Yep, so only the exact link and the API requests will return an error. Github will redirect everything else.

**Comment by waldyrious** [comment] 2019-11-21 19:49
Evidently we wouldn't simply swap things around all of a sudden, unannounced. This change would have to be synced with client maintainers.

Also, we could re-register the org name if we wanted to set up renaming notices or prevent others from taking over the name, etc. Look, none of this is meant to be painless or easy. But we are a capable and technically competent community -- I don't think we should be stopped from taking this sort of decision based on possible technical challenges of a project rename. If we do think the current name is better, even assuming a transition to another name would be completely seamless, then it's fair to stick with it on its merits -- but let's not do so based merely on the technical difficulty of adopting an alternative.

**Comment by mebeim** [comment] 2019-11-21 21:51
@waldyrious valid point. I genuinely think the current name is better though.

**Comment by sbrl** [comment] 2019-11-22 15:02
Personally I've always used `tldr-pages` myself. I agree with @mebeim  and @ostera here personally.

**Comment by zdroid** [comment] 2019-11-22 17:59
@waldyrious I'm not completely for `.sh` extension since it's generally used for projects developed in Shell only. However it nicely indicates the project's use, and that's a big plus. :+1:

**Comment by waldyrious** [comment] 2019-11-22 21:43
> Personally I've always used `tldr-pages` myself.

@sbrl the problem is that previous suggestions (in the older comments of this thread) to use a hyphenized form were met with a lukewarm reception, so unless we can swap that sentiment, we'd be stuck with the awkward two-word, unclearly separated "tldr pages". Any thoughts about that? 😕

**Comment by mebeim** [comment] 2019-11-23 18:08
What's the hyphen thing? Whether to use "tldr-pages" or "TLDR pages" would of course depend on the context. If we talk about the GH repo/url user we say "tldr-pages", otherwise "TLDR pages". I don't see a problem. 

@sbrl are you suggesting to use "tldr-pages" *as the project name* instead of "TLDR pages"? That wouldn't make sense IMHO.

@zdroid how does `.sh` indicate the project's use? `.sh` makes me think of a shell script, not a collection of manual pages. Could you elaborate on that?

**Comment by zdroid** [comment] 2019-11-23 18:32
@mebeim for me it's more indicative of being used in shell. I have to say tldr-pages sounds more like it's a print publication and not a computer program.

**Comment by waldyrious** [comment] 2019-11-23 21:39
> If we talk about the GH repo/url user we say "tldr-pages", otherwise "TLDR pages".

@mebeim please note that at the start of this thread there was some discussion aboout using the capitalized version, and the consensus seemed to be that the lowercase version was preferable.

**Comment by mebeim** [comment] 2019-11-24 16:15
@waldyrious I was just differentiating between the two alternatives with or without hyphen, I already said that case wasn't important for me.

**Comment by zdroid** [comment] 2019-12-15 00:45
Reviewing most of the project's repositories, it seems this and #1192 are the omnipresent issues. Website, docs and clients all have own version of brand name and description.

I suggest we focus on these two (quite correlated) issues over any other, in order to finally move on. The issues hurt the project's branding, promotion, portability (clients) and on top of that, confuses everyone involved. However, I am sure we'll be able to solve this as soon as possible. :hugs:

**Comment by zdroid** [comment] 2019-12-17 21:54
ping @waldyrious @mebeim @agnivade @pxgamer 

(it seems @sbrl agreed with the point)

**Comment by mebeim** [comment] 2019-12-18 00:17
@zdroid I don't think capitalization is a problem, but I nonetheless agree that "tldr pages" should be the name.

**Comment by agnivade** [comment] 2019-12-18 03:46
I have already given my opinion above. I am neutral.

**Comment by zdroid** [comment] 2019-12-18 09:43
So we agreed on this? Maybe it's the time to close the issue?

**Comment by mebeim** [comment] 2019-12-19 06:55
@zdroid doesn't seem like we all agree to me, I *think* the majority prefers "tldr pages" but I'm not sure, cannot read all the history now.

**Comment by zdroid** [comment] 2019-12-19 10:11
I meant the majority of course, it's quite impossible everybody completely agrees on something.

**Comment by sbrl** [comment] 2019-12-20 19:57
See [this comment](https://github.com/tldr-pages/tldr/issues/2339#issuecomment-423808210) and [this comment](https://github.com/tldr-pages/tldr/issues/3041#issuecomment-495004004) @zdroid :-)

**Comment by waldyrious** [comment] 2019-12-24 15:45
I'll give a shot at summarizing the main points of the discussion above (I'm interpreting consensus as no strong objections):

- **Semicolon**: there is consensus to _not_ use it (so `tldr` instead of `tl;dr`)
- **Capitalization**: there is consensus to use lowercase (so `tldr` instead of `TLDR`)
- **Rebranding**: no consensus to change. The closest alternative that garnered some support was "miniman", but there was opposition due to the "tldr" name being too ingrained now. Even [the proposal](https://github.com/tldr-pages/tldr/issues/1109#issuecomment-556620205) to make a softer change towards "tldr.sh" had a lukewarm reception, with no clear preference.
- **Hyphenization**: no consensus. Using a hyphenized form was proposed [here](https://github.com/tldr-pages/tldr/issues/1109#issuecomment-255104786) and [here](https://github.com/tldr-pages/tldr/issues/1109#issuecomment-262176332), but was argued against [here](https://github.com/tldr-pages/tldr/issues/1109#issuecomment-262217401); additional signals (comments, reaction) did not accumulate significantly in favor either approach.

Gathering a more global view of what has been discussed, I'd say there are only three alternatives with any chance of being adopted:
1. The progressive option: Biting the bullet and making the change to **miniman**, with the understanding that there are potential downsides but they are manageable, and balanced out by the [upsides](https://github.com/tldr-pages/tldr/issues/1109#issuecomment-326894332) (including [enthusiasm](https://github.com/tldr-pages/tldr/issues/1109#issuecomment-302388562) by [various](https://github.com/tldr-pages/tldr/issues/1109#issuecomment-326822759) [community](https://github.com/tldr-pages/tldr/issues/1109#issuecomment-326827966) [members](https://github.com/tldr-pages/tldr/issues/1109#issuecomment-327083318), [even the project creator](https://github.com/tldr-pages/tldr/issues/1109#issuecomment-302383621)!);
2. The moderate option: Consolidating in **tldr.sh** as a simpler, shorter and more distinctively "brand-y" name;
3. The conservative option: Sticking with **tldr pages** (this exact spelling: no capitals, no semicolon, no hyphen) as the evil we know, to avoid the inconveniences of changing the name and benefit from the historical weight of the name.

I must admit 😢 that option 3 seems to be the only one that nobody objects to, so if you guys agree this assessment is correct, we can close the issue with that decision.

I would only ask for a compromise in order to reduce the "tldr pages page" issue: can we start referring to each individual file as an "entry" rather than a "page"? That's not part of the branding itself, but would greatly facilitate it, and would remove the ambiguity of the project name being "tldr pages" vs. "tldr".

**Comment by sbrl** [comment] 2019-12-24 18:29
Great summary @waldyrious! This is indeed a thorny issue. Personally I've always called it a "tldr page", but a "tldr-pages entry" would be fine too. If this is the case we should update any documentation where this is referenced.

I've always used `tldr-pages` myself, but that's only because that's the name of the org.

**Comment by zdroid** [comment] 2019-12-24 20:03
It doesn't seem wrong to use the term *page(s)* for the actual pages. tldr pages as a project is basically a collection of those pages. The more terms we add, the more complicated documentation becomes. I'm against defining more terms such as *entries*.

**Comment by waldyrious** [comment] 2019-12-25 23:24
@zdroid please note that the suggestion of using "entries" is not frivolous: it's only to overcome the _existing_ issue of referring to an individual file as a "tldr page" (which is ambiguous by making it seem like the project's name is "tldr" alone, which is precisely the type of confusion this issue was created to address) or as "tdlr pages page" (which is very awkward and essentially unusable).

That's one of the reasons I was hoping for alternative project names that didn't include "pages" in the name (i.e. _tldr.sh_ or _miniman_), because those would automatically avoid the issue. But if we can't agree to make such a change, then the issue needs to be addressed elsewhere, hence the proposal to use "entries".

**Comment by mebeim** [comment] 2019-12-26 05:59
I think you summarized that pretty well @waldyrious. I don't think I've ever referred to a page as "tldr page". Why not just use the word "page" alone? It probably depends on the context, but I don't really see this as an issue.

**Comment by waldyrious** [comment] 2019-12-26 09:58
> Why not just use the word "page" alone?

It's very context-sensitive and would make it hard to talk about tldr pages among other page-like entities (e.g. man pages, actual pagination of content, etc.)

Of course, we can _live_ with the ambiguity (we have done just that so far); I was just suggesting a way that we could get rid of it without much effort (IMO).

**Comment by zdroid** [comment] 2019-12-26 13:51
@waldyrious It's the same way for man pages and I don't see them having any issues. The command is called `tldr` (just like `man`) and its pages are called `tldr pages` (just like `man pages`), which is what the project mostly is.

**Comment by waldyrious** [comment] 2019-12-26 17:33
That's a good point. I don't agree that there are no issues, as I described in several comments above, but I can accept that they're not super-problematic. Do you all prefer keeping "page" as the name of each entry, then?

**Comment by mebeim** [comment] 2019-12-26 17:37
@waldyrious I do, I don't think other options would help that much.

**Comment by andrik** [comment] 2019-12-26 18:17
@waldyrious 

I see your point but I think we could keep _page_

**Comment by zdroid** [comment] 2020-05-02 19:26
To be fair, this seems to have already been decided. `tldr pages` is the standard name for the whole project, and `tldr` for this repository and the command-line clients. I'm in for closing this and moving on with more important issues.

**Comment by agnivade** [comment] 2020-05-03 09:39
Sounds reasonable to me. I just did a quick scan of the last couple of comments, and it seems like the discussion was about what to call a single item in our repo - and that seems to have converged on "page".

To conclude:

- Project name remains as - "tldr pages". Exact spelling, no semicolon, no hypen, and not just "tldr" too.
- A single item in the project will be termed as a "page". Similar to man pages, a page here implies a page from the "tldr pages" project. Short and simple.

Thanks everyone who participated in this, and special thanks to @waldyrious who took a lot of pain in steering the discussion in a coherent way ! Really glad to see how this turned out.

**Comment by waldyrious** [comment] 2020-05-05 22:48
Thanks guys for wrapping this up. I think we need to remove the remnants of the semicolon, right? I know it's present in the [banner](https://github.com/tldr-pages/tldr/blob/master/images/banner.svg); do you know if any additional instances remain?

**Comment by agnivade** [comment] 2020-05-06 04:09
Thanks @waldyrious. That sounds great. Let's open a new one ? This issue is already overloaded with discussion on the brand name. I think a new issue to track the changes to be made might be more clear.

**Comment by zdroid** [comment] 2020-05-06 08:26
@waldyrious I suggest you open a PR with that change. You don't have to work on it extensively, as the other contributors can finish the job. :)
Also, the descriptions of other repos in this org should be updated.

**Comment by waldyrious** [comment] 2020-05-06 09:55
Makes sense @agnivade. I'll work on this tomorrow night, time permitting.

**Closed** 2020-05-10 18:41 UTC
Labels: decision
