### ISSUE TITLE
page request: git subcommand

### ISSUE THREAD

**Issue by diegovrocha** [tldr-pages/tldr#8137] opened 2022-06-17 12:05 UTC
### Command description

Please, let's document **git subcommands**

### OS

General

**Comment by mfrw** [comment] 2022-06-18 06:38
Hi @diegovrocha, do you have any specific subcommands in mind that do not have a page yet & are not covered by:
- https://github.com/tldr-pages/tldr/issues/3953

Please feel free to use the above tracking issue instead of creating a new one :)

Thank you.

Closing this issue as a duplicate of #3953

**Closed by mfrw** 2022-06-18 06:38 UTC
Labels: new command
