### ISSUE TITLE
Page request: nnn

### ISSUE THREAD

**Issue by osbm** [tldr-pages/tldr#13218] opened 2024-07-03 11:31 UTC
### Command description

Popular terminal file manager. with 18k stars on github

I also see a very old PR from 2019. (#3071)

### Documentation

https://github.com/jarun/nnn/wiki

### Platform

Common

### VCS repository link (e.g. GitHub, GitLab)

https://github.com/jarun/nnn

**Comment by abhishek-agrl** [comment] 2024-07-07 17:18
Hi, I would like to contribute to this and have added a new pull request - https://github.com/tldr-pages/tldr/pull/13239

**Comment by spageektti** [comment] 2024-07-07 17:22
> Hi, I would like to contribute to this and have added a new pull request - https://github.com/tldr-pages/tldr/pull/13239

When you open a PR that fixes a issue, you can add `Closes #issue-id` so that the issue is closed when the PR is merged.

**Comment by abhishek-agrl** [comment] 2024-07-07 17:29
I apologise for the oversight, will keep this in mind. Thanks :)

**Closed** 2024-07-08 21:15 UTC
Labels: new command, help wanted
