### ISSUE TITLE
How to specify that a command (e.g. `ip addr`) is a synonym for another command (`ip address`)?

### ISSUE THREAD

**Issue by ldorigo** [tldr-pages/tldr#4049] opened 2020-05-16 06:50 UTC
Is there some logic currently in place for this? Or should it just be added as a comment on the main command?  It would be nice if when a user does `tldr ip addr`, he automatically received the page for `tldr ip address`.

**Comment by principis** [comment] 2020-05-16 07:56
At the moment there is no system in place because tldr is just markdown files.

Partially off-topic comment, `ip a` is a more common shortcut for `ip address`

**Comment by sbrl** [comment] 2020-05-21 11:41
Yeah, we don't yet have a synonym system. That's been discussed in #787 IIRC

**Comment by zdroid** [comment] 2020-06-20 18:28
@sbrl @ldorigo I suggest moving this to #787 as it is essentially the same. System that would support that would also support this.

**Comment by sbrl** [comment] 2020-06-21 20:22
Indeed @zdroid. We should close this as a duplicate of #787.

**Closed** 2020-06-21 20:23 UTC
